name: publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest,
    steps:
      - uses: actions/checkout@v5
      - name: Set up uv & Python
        # uses: actions/setup-python@v4
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
          version: "0.10.0"
      - name: Build distribution
        run: make build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
